/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DigitsRouteImport } from './routes/digits'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as SystemRouteImport } from './routes/system'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogModelIdRouteImport } from './routes/catalog.$modelId'
import { Route as PartsIndexRouteImport } from './routes/parts.index'
import { Route as PartsPartIdRouteImport } from './routes/parts.$partId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitsRoute = DigitsRouteImport.update({
  id: '/digits',
  path: '/digits',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogModelIdRoute = CatalogModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => CatalogRoute,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartsRoute,
} as any)
const PartsPartIdRoute = PartsPartIdRouteImport.update({
  id: '/$partId',
  path: '/$partId',
  getParentRoute: () => PartsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/compare': typeof CompareRoute
  '/digits': typeof DigitsRoute
  '/parts': typeof PartsRouteWithChildren
  '/system': typeof SystemRoute
  '/catalog/$modelId': typeof CatalogModelIdRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/parts/': typeof PartsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/digits': typeof DigitsRoute
  '/system': typeof SystemRoute
  '/catalog/$modelId': typeof CatalogModelIdRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/catalog': typeof CatalogIndexRoute
  '/parts': typeof PartsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/compare': typeof CompareRoute
  '/digits': typeof DigitsRoute
  '/parts': typeof PartsRouteWithChildren
  '/system': typeof SystemRoute
  '/catalog/$modelId': typeof CatalogModelIdRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/parts/': typeof PartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/compare'
    | '/digits'
    | '/parts'
    | '/system'
    | '/catalog/$modelId'
    | '/parts/$partId'
    | '/catalog/'
    | '/parts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/digits'
    | '/system'
    | '/catalog/$modelId'
    | '/parts/$partId'
    | '/catalog'
    | '/parts'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/compare'
    | '/digits'
    | '/parts'
    | '/system'
    | '/catalog/$modelId'
    | '/parts/$partId'
    | '/catalog/'
    | '/parts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  CompareRoute: typeof CompareRoute
  DigitsRoute: typeof DigitsRoute
  PartsRoute: typeof PartsRouteWithChildren
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digits': {
      id: '/digits'
      path: '/digits'
      fullPath: '/digits'
      preLoaderRoute: typeof DigitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/$modelId': {
      id: '/catalog/$modelId'
      path: '/$modelId'
      fullPath: '/catalog/$modelId'
      preLoaderRoute: typeof CatalogModelIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/parts/': {
      id: '/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof PartsRoute
    }
    '/parts/$partId': {
      id: '/parts/$partId'
      path: '/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof PartsPartIdRouteImport
      parentRoute: typeof PartsRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogModelIdRoute: typeof CatalogModelIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogModelIdRoute: CatalogModelIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface PartsRouteChildren {
  PartsPartIdRoute: typeof PartsPartIdRoute
  PartsIndexRoute: typeof PartsIndexRoute
}

const PartsRouteChildren: PartsRouteChildren = {
  PartsPartIdRoute: PartsPartIdRoute,
  PartsIndexRoute: PartsIndexRoute,
}

const PartsRouteWithChildren = PartsRoute._addFileChildren(PartsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRouteWithChildren,
  CompareRoute: CompareRoute,
  DigitsRoute: DigitsRoute,
  PartsRoute: PartsRouteWithChildren,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
